[package]
name = "display_mat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpi-led-matrix = { version = "0.2.2", features = ["embeddedgraphics"] } 
signal-hook = "0.3.10"