[package]
name = "entry"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
particles = { path = "../particles" }
display_gui = { path = "../display_gui" }
display_mat = { path = "../display_mat" }
